### ISSUE TITLE
Configure the GUI to not crash whenever we open it with buggy not connected

### ISSUE THREAD

**Issue by VivaanBahl** [CMU-Robotics-Club/RoboBuggy#203]
This works on Vasu's computer but not on the surface. Would be nice to figure out what's going on

**Comment by VivaanBahl** [comment]
```
Starting GUI
Populated!
Starting Logging
Initializing IMU Serial Connection
Stable Library
=========================================
Native lib Version = RXTX-2.2-20081207 Cloudhopper Build rxtx.cloudhopper.net
Java lib Version   = RXTX-2.1-7
WARNING:  RXTX Version mismatch
	Jar version = RXTX-2.1-7
	native lib Version = RXTX-2.2-20081207 Cloudhopper Build rxtx.cloudhopper.net
Unable to connect to necessary device on COM6
gnu.io.NoSuchPortException
Trying to close the window!
	at gnu.io.CommPortIdentifier.getPortIdentifier(CommPortIdentifier.java:218)
	at com.roboclub.robobuggy.main.mainFile.connect(mainFile.java:67)
	at com.roboclub.robobuggy.main.mainFile.bringup_sim(mainFile.java:123)
	at com.roboclub.robobuggy.main.mainFile.main(mainFile.java:52)
```

**Comment by TrevorDecker** [comment]
This has been fixed in logging play back
